#basic commands of Unix/Linux

alias l='ls -A--color=always'
alias ls='ls  --color=auto'
alias ll='ls -alhF --color=always'
alias la='ls -a --color=always'
alias vi='vim'
alias hist='history | grep'
alias cls='clear'
alias cpan='sudo perl -MCPAN -e shell'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# refrash config
alias srcprofile='source ~/.bashrc'
alias srcp='source ~/.bashrc'
alias viprofile='vim ~/.bashrc'
alias vipr='vim ~/.bashrc'

# for apt-get part
alias install="sudo apt-get install"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias dist-upgrade="sudo apt-get dist-upgrade"
alias uninstall="sudo apt-get remove"
alias remove="sudo apt-get remove"
alias clean="sudo apt-get clean"
alias autoremove="sudo apt-get autoremove"
alias autoclean="sudo apt-get autoclean"

# for the frequently used locations
alias dl='cd ~/Downloads'
alias dc="cd ~/Documents"
alias bi="cd ~/Bin"
alias mu="cd ~/Music"
alias pic="cd ~/pictures"
alias des="cd ~/Desktop"
alias edg="cd ~/Edge"

# bioinfo
alias trimmomatic="java -jar /software/Trimmomatic-0.33/trimmomatic-0.33.jar"

# for remote operations
alias rayfromadmin="scp -r -p admin@10.157.14.13:/Users/admin/"

